# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablechange',
            old_name='five',
            new_name='ten',
        ),
    ]
